# coding: utf-8
# ALL NN
IMAGE_SIZE = 28
OUTPUT_SIZE = 10
IMAGE_CHANNELS = 1
LEARNING_RATE_BASE = 0.8
LEARNING_RATE_DECAY = 0.99
MOVING_AVERAGE_DECAY = 0.99
REGULARIZATION_RATE = 0.0001
MODEL_NAME = "mnist_model"
NNIST_DATA_PATH = "../data/res"

# DNN
DNN_INPUT_SIZE = IMAGE_SIZE * IMAGE_SIZE
DNN_LAYER1_SIZE = 500
DNN_BATCH_SIZE = 100
DNN_TRAINING_STEPS = 30000
DNN_MODEL_SAVE_PATH = "data/models/dnn"
DNN_TEST_RESULT_PATH= "data/result/dnn.txt"

# CNN
CNN_INPUT_SIZE = 784
CNN_BATCH_SIZE = 100
CNN_TRAINING_STEPS = 6000
CNN_MODEL_SAVE_PATH = "data/models/cnn"
CNN_CONV1_DEEP = 32
CNN_CONV1_SIZE = 5
CNN_CONV2_DEEP = 64
CNN_CONV2_SIZE = 5
CNN_FC_SIZE = 512
CNN_TEST_RESULT_PATH= "data/result/cnn.txt"

# RNN
RNN_INPUT_SIZE = 28    # 特征维度，字符图片的每一行看成输入特征
RNN_STEP_SIZE = 28    # 每张字符图片共有28行, LSTM 28次
RNN_HIDDEN_SIZE = 128  # 隐藏单元个数
RNN_LEARNING_RATE = 0.001
RNN_TRAINING_STEPS = 2000
RNN_BATCH_SIZE = 32
RNN_MODEL_SAVE_PATH = "data/models/rnn"
RNN_TEST_RESULT_PATH= "data/result/rnn.txt"


# learning_rate = 0.001
# training_iters = 100000
# batch_size = 32
# display_step = 10

